import { AIModelMeta } from './types';

export const IPORTAL_MODELS: AIModelMeta[] = [
  // --- Virtual Unified iportal-ai Models ---
  {
    id: 'iportal-ai',
    name: 'iportal-ai (GPT OSS 120B / Smart Auto)',
    provider: 'groq',
    realModelId: 'openai/gpt-oss-120b',
    category: 'smart',
    description: 'Eng optimal bepul AI modeli. Avtomatik ravishda eng tez va sifatli provayderni tanlaydi.',
    contextWindow: 131072,
    speed: '~350 tok/s',
    isFree: true,
  },
  {
    id: 'iportal-ai-fast',
    name: 'iportal-ai Turbo (GPT OSS 20B / Fast)',
    provider: 'groq',
    realModelId: 'openai/gpt-oss-20b',
    category: 'fast',
    description: 'Ultra tezkor javoblar (800+ tok/s). Qisqa savol-javob va tezkor yordam uchun.',
    contextWindow: 131072,
    speed: '~800 tok/s',
    isFree: true,
  },
  {
    id: 'iportal-ai-reasoning',
    name: 'iportal-ai Thinking (Qwen 3.6 27B / DeepSeek)',
    provider: 'groq',
    realModelId: 'qwen/qwen3.6-27b',
    category: 'reasoning',
    description: 'Chuqur fikrlovchi va mantiqiy xulosalar chiqaruvchi yangi Qwen 3.6 / DeepSeek modeli.',
    contextWindow: 131072,
    speed: '~250 tok/s',
    isFree: true,
  },
  {
    id: 'iportal-ai-pro',
    name: 'iportal-ai Pro (GPT OSS 120B)',
    provider: 'groq',
    realModelId: 'openai/gpt-oss-120b',
    category: 'smart',
    description: 'Katta bilimlar bazasi va chuqur tahlilga ega GPT OSS 120B Flagship modeli.',
    contextWindow: 131072,
    speed: '~300 tok/s',
    isFree: true,
  },
  {
    id: 'iportal-ai-coder',
    name: 'iportal-ai Code Master (GPT OSS 120B)',
    provider: 'groq',
    realModelId: 'openai/gpt-oss-120b',
    category: 'code',
    description: 'Dasturlash, kod yozish, tahlil qilish va xatolarni tuzatish uchun ixtisoslashgan model.',
    contextWindow: 131072,
    speed: '~300 tok/s',
    isFree: true,
  },

  // --- Direct Provider Specific Models ---
  {
    id: 'groq/gpt-oss-120b',
    name: 'GPT OSS 120B (Groq LPU)',
    provider: 'groq',
    realModelId: 'openai/gpt-oss-120b',
    category: 'smart',
    description: 'Groq LPU chipida ishlaydigan GPT OSS 120B Flagship modeli.',
    contextWindow: 131072,
    speed: '~350 tok/s',
    isFree: true,
  },
  {
    id: 'groq/qwen3.6-27b',
    name: 'Qwen 3.6 27B Reasoning (Groq)',
    provider: 'groq',
    realModelId: 'qwen/qwen3.6-27b',
    category: 'reasoning',
    description: 'Ultra tezkor mulohaza yurituvchi Qwen 3.6 27B modeli.',
    contextWindow: 131072,
    speed: '~400 tok/s',
    isFree: true,
  },
  {
    id: 'groq/gpt-oss-20b',
    name: 'GPT OSS 20B Turbo (Groq)',
    provider: 'groq',
    realModelId: 'openai/gpt-oss-20b',
    category: 'fast',
    description: 'Ultra tezkor GPT OSS 20B modeli.',
    contextWindow: 131072,
    speed: '~800 tok/s',
    isFree: true,
  },
  {
    id: 'gemini/gemini-2.0-flash',
    name: 'Google Gemini 2.0 Flash',
    provider: 'gemini',
    realModelId: 'gemini-2.0-flash',
    category: 'smart',
    description: 'Google AI Studio bepul Gemini 2.0 Flash.',
    contextWindow: 1048576,
    speed: '~200 tok/s',
    isFree: true,
  },
  {
    id: 'sambanova/deepseek-r1-70b',
    name: 'DeepSeek R1 Distill 70B (SambaNova)',
    provider: 'sambanova',
    realModelId: 'DeepSeek-R1-Distill-Llama-70B',
    category: 'reasoning',
    description: 'SambaNova SN40L chipida ishlaydigan DeepSeek R1 70B.',
    contextWindow: 64000,
    speed: '~180 tok/s',
    isFree: true,
  },
  {
    id: 'cerebras/llama3.1-70b',
    name: 'Llama 3.1 70B (Cerebras CS-3)',
    provider: 'cerebras',
    realModelId: 'llama3.1-70b',
    category: 'fast',
    description: 'Cerebras Wafer-Scale Engine tezligi (450+ tok/s).',
    contextWindow: 8192,
    speed: '~450 tok/s',
    isFree: true,
  },
  {
    id: 'openrouter/free-auto',
    name: 'OpenRouter Free Router',
    provider: 'openrouter',
    realModelId: 'meta-llama/llama-3.3-70b-instruct:free',
    category: 'general',
    description: 'OpenRouter platformasidagi bepul modellar klasteri.',
    contextWindow: 64000,
    speed: '~100 tok/s',
    isFree: true,
  },
  {
    id: 'mistral/mistral-small',
    name: 'Mistral Small Latest',
    provider: 'mistral',
    realModelId: 'mistral-small-latest',
    category: 'general',
    description: 'Mistral AI bepul tier modeli.',
    contextWindow: 32768,
    speed: '~140 tok/s',
    isFree: true,
  }
];

export function findModel(modelId: string): AIModelMeta {
  const found = IPORTAL_MODELS.find(m => m.id.toLowerCase() === modelId.toLowerCase());
  if (found) return found;
  return IPORTAL_MODELS[0];
}
