import { AIModelMeta } from './types';

export const IPORTAL_MODELS: AIModelMeta[] = [
  // --- Virtual Unified iportal-ai Models ---
  {
    id: 'iportal-ai',
    name: 'iportal-ai (Smart Auto)',
    provider: 'groq',
    realModelId: 'llama-3.3-70b-versatile',
    category: 'smart',
    description: 'Eng optimal bepul AI modeli. Avtomatik ravishda eng tez va sifatli provayderni tanlaydi.',
    contextWindow: 128000,
    speed: '~350 tok/s',
    isFree: true,
  },
  {
    id: 'iportal-ai-fast',
    name: 'iportal-ai Turbo (Fastest)',
    provider: 'cerebras',
    realModelId: 'llama3.1-8b',
    category: 'fast',
    description: 'Ultra tezkor javoblar (1000+ tok/s). Qisqa savol-javob va tezkor yordam uchun.',
    contextWindow: 8192,
    speed: '~1000 tok/s',
    isFree: true,
  },
  {
    id: 'iportal-ai-reasoning',
    name: 'iportal-ai Thinking (Deep Reasoning)',
    provider: 'sambanova',
    realModelId: 'DeepSeek-R1-Distill-Llama-70B',
    category: 'reasoning',
    description: 'Chuqur fikrlovchi va mantiqiy xulosalar chiqaruvchi DeepSeek R1 modeli.',
    contextWindow: 64000,
    speed: '~150 tok/s',
    isFree: true,
  },
  {
    id: 'iportal-ai-pro',
    name: 'iportal-ai Pro (Gemini 2.0 Flash)',
    provider: 'gemini',
    realModelId: 'gemini-2.0-flash',
    category: 'smart',
    description: 'Katta kontekst (1M token) va eng so\'nggi bilimlar bazasiga ega Gemini 2.0 Flash.',
    contextWindow: 1048576,
    speed: '~200 tok/s',
    isFree: true,
  },
  {
    id: 'iportal-ai-coder',
    name: 'iportal-ai Code Master',
    provider: 'sambanova',
    realModelId: 'Qwen2.5-Coder-32B-Instruct',
    category: 'code',
    description: 'Dasturlash, kod yozish va xatolarni tuzatish uchun ixtisoslashgan model.',
    contextWindow: 32768,
    speed: '~220 tok/s',
    isFree: true,
  },

  // --- Direct Provider Specific Models ---
  {
    id: 'groq/llama-3.3-70b',
    name: 'Meta Llama 3.3 70B (Groq)',
    provider: 'groq',
    realModelId: 'llama-3.3-70b-versatile',
    category: 'general',
    description: 'Groq LPU chipida ishlaydigan Llama 3.3 70B.',
    contextWindow: 128000,
    speed: '~300 tok/s',
    isFree: true,
  },
  {
    id: 'groq/llama-3.1-8b',
    name: 'Meta Llama 3.1 8B Instant (Groq)',
    provider: 'groq',
    realModelId: 'llama-3.1-8b-instant',
    category: 'fast',
    description: 'Ultra tezkor Llama 3.1 8B modeli.',
    contextWindow: 8192,
    speed: '~750 tok/s',
    isFree: true,
  },
  {
    id: 'gemini/gemini-2.0-flash',
    name: 'Google Gemini 2.0 Flash',
    provider: 'gemini',
    realModelId: 'gemini-2.0-flash',
    category: 'smart',
    description: 'Google AI Studio bepul Gemini 2.0 Flash.',
    contextWindow: 1048576,
    speed: '~200 tok/s',
    isFree: true,
  },
  {
    id: 'gemini/gemini-1.5-flash',
    name: 'Google Gemini 1.5 Flash',
    provider: 'gemini',
    realModelId: 'gemini-1.5-flash',
    category: 'smart',
    description: 'Google AI Studio bepul Gemini 1.5 Flash.',
    contextWindow: 1048576,
    speed: '~220 tok/s',
    isFree: true,
  },
  {
    id: 'sambanova/deepseek-r1-70b',
    name: 'DeepSeek R1 Distill 70B (SambaNova)',
    provider: 'sambanova',
    realModelId: 'DeepSeek-R1-Distill-Llama-70B',
    category: 'reasoning',
    description: 'SambaNova SN40L chipida ishlaydigan DeepSeek R1 70B.',
    contextWindow: 64000,
    speed: '~180 tok/s',
    isFree: true,
  },
  {
    id: 'cerebras/llama3.1-70b',
    name: 'Llama 3.1 70B (Cerebras CS-3)',
    provider: 'cerebras',
    realModelId: 'llama3.1-70b',
    category: 'fast',
    description: 'Cerebras Wafer-Scale Engine tezligi (450+ tok/s).',
    contextWindow: 8192,
    speed: '~450 tok/s',
    isFree: true,
  },
  {
    id: 'openrouter/free-auto',
    name: 'OpenRouter Free Router',
    provider: 'openrouter',
    realModelId: 'meta-llama/llama-3.3-70b-instruct:free',
    category: 'general',
    description: 'OpenRouter platformasidagi bepul modellar klasteri.',
    contextWindow: 64000,
    speed: '~100 tok/s',
    isFree: true,
  },
  {
    id: 'mistral/mistral-small',
    name: 'Mistral Small Latest',
    provider: 'mistral',
    realModelId: 'mistral-small-latest',
    category: 'general',
    description: 'Mistral AI bepul tier modeli.',
    contextWindow: 32768,
    speed: '~140 tok/s',
    isFree: true,
  }
];

export function findModel(modelId: string): AIModelMeta {
  const found = IPORTAL_MODELS.find(m => m.id.toLowerCase() === modelId.toLowerCase());
  if (found) return found;
  // Default to universal iportal-ai
  return IPORTAL_MODELS[0];
}
